vich_uploader:
    db_driver: orm

    mappings:
        img_book:
            uri_prefix: /uploads/imageBooks
            upload_destination: '%kernel.project_dir%/public/uploads/imageBooks'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
